---
title: "Data Wrangling 1"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load the libraries

```
library(tidyr)
library(readr)
library(dplyr)
```

### Read data from a CSV file

```
data <- read_csv("refine_original.csv", col_names = TRUE)
```

### Convert the company names to all lower case and save the revised tibble

```
data <- mutate(data, company = tolower(data$company))
```

### Search for company names that are not correctly spelled, make the correction, and update

```
data$company <- gsub("^[pf].*", "philips", data$company)
data$company <- gsub("^a.*", "azko", data$company)
data$company <- gsub("^v.*", "van houten", data$company)
data$company <- gsub("^u.*", "unilever", data$company)
```

### Separate the product code and product number into separate columns 
##### (Add two new columns called product_code and product_number and remove old column 'Product code / number'

```
data <- separate(data, "Product code / number", c("product_code", "product_number"), sep="-")
```

### Add a column with the product category for each record based on the product codes

```
data <- mutate(data, product_category = product_code)

data$product_category <- gsub("p", "Smartphone", data$product_category) 
data$product_category <- gsub("v", "TV", data$product_category) 
data$product_category <- gsub("x", "Laptop", data$product_category) 
data$product_category <- gsub("q", "Tablet", data$product_category) 
```

### Create a new column full_address
##### Concatenate the three address fields (address, city, country), separated by commas

```
data <- unite(data, full_address, c(address, city, country), sep = ",")
```

### Create dummy variables for companies

```
data <- mutate(data, company_philips = ifelse(company == "philips",1,0))
data <- mutate(data, company_akzo = ifelse(company == "azko",1,0))
data <- mutate(data, company_van_houten = ifelse(company == "van houten",1,0))
data <- mutate(data, company_unilever = ifelse(company == "unilever",1,0))
```

### Create dummy variables for product categories

```
data <- mutate(data, product_smartphone = ifelse(product_code == "p",1,0))
data <- mutate(data, product_tv = ifelse(product_code == "v",1,0))
data <- mutate(data, product_laptop = ifelse(product_code == "x",1,0))
data <- mutate(data, product_tablet = ifelse(product_code == "q",1,0))
```

### Re-order the columns for clarity

```
data <- data[,c(1,7:10,2:3,6,11:14,4,5)]
```

### View the data

```
View(arrange(data, company))
```

### Export the data to a new CSV file titled "refine_clean.csv"

```
write_csv(data, "refine_clean.csv")
```